ElectionProject/ElectionProject/Controllers/ElectionsController.cs
using System;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ElectionProject.Models;
namespace ElectionProject.Controllers
{

    public class ElectionsController : Controller
    {


        private readonly ElectionContext _context;

        public ElectionsController(ElectionContext context)
        {
            _context = context;
        }

        // GET: Circuits
        public async Task<IActionResult> Index()
        {
            return View(await _context.Election.ToListAsync());
        }

        // GET: Circuits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var election = await _context.Election
                .FirstOrDefaultAsync(m => m.Id == id);
            if (election == null)
            {
                return NotFound();
            }

            return View(election);
        }

        // GET: Circuits/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Circuits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Year,Tour, StartDate, EndDate, HeadOfCvk")] Election election)
        {
            if (ModelState.IsValid)
            {
                _context.Add(election);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(election);
        }

        // GET: Circuits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var election = await _context.Election.FindAsync(id);
            if (election == null)
            {
                return NotFound();
            }
            return View(election);
        }

        // POST: Circuits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Year,Tour, StartDate, EndDate, HeadOfCvk")] Election election)
        {
            if (id != election.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(election);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ElectionExists(election.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(election);
        }

        // GET: Circuits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var election = await _context.Circuit
                .FirstOrDefaultAsync(m => m.Id == id);
            if (election == null)
            {
                return NotFound();
            }

            return View(election);
        }

        // POST: Circuits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var election = await _context.Election.FindAsync(id);
            _context.Election.Remove(election);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ElectionExists(int id)
        {
            return _context.Election.Any(e => e.Id == id);
        }
    }
}

ElectionProject/ElectionProject/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ElectionProject.Models;
using Microsoft.EntityFrameworkCore;
using ElectionProject.ModelView;
namespace ElectionProject.Controllers
{
    public class VoteController: Controller
    {
        private readonly ElectionContext _context;

        public VoteController(ElectionContext context)
        { 
            _context = context;
        }

        public IActionResult VoteFinal()
        {
            return View();
        }

        public IActionResult Index()
        {
            var sql = $@"select * from election
                          where end_date>='1999-11-14';";
            var election = _context.Set<Election>().FromSql(sql).ToList();
            return View(election);
        }

        public async Task<IActionResult> Vote(int electionId)
        {
            var sql = $@"select candidate.id, citizen.last_name, candidate.election_id from candidate
                         join citizen on citizen.id=candidate.citizen_id
                         where candidate.election_id={electionId};";
            var candidates = _context.Query<VoteResult>().FromSql(sql).ToList();

            return View(candidates);
        }

        [HttpPost]
        public async Task<IActionResult> Vote(int electionId,int candidateId, string citizenEmail)
        {
            var sql = $@"select district_id, id from citizen
                           where email = '{citizenEmail}' ;";
            
            var candidate = _context.Query<DistrictId>().FromSql(sql).ToList();
            int distrctId=candidate.ElementAt(0).district_id;
            int citizenId = candidate.ElementAt(0).id;
            var sql2 = $@"select * from vote
                          where citizen_id={citizenId} and election_id={electionId};";
            var vote = _context.Set<Vote>().FromSql(sql2).ToList();
            if (vote.Capacity == 0)
            {

                var count = _context.Vote.Count();
                int id = (Int32)count; id++;

                var sqlResult = $@"insert into vote values ({id},{electionId},{distrctId},{citizenId},{candidateId});";
                var Result = _context.Query<Insert>().FromSql(sqlResult).ToList();

                return Redirect("Index");
            }
            else
            {
                return Redirect("VoteFinal");
            }
        }


    }

}

ElectionProject/ElectionProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElectionProject</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ЦВК</a>
            </div>
            <div class="navbar-collapse collapse">


                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">

                        <li><a asp-area="" asp-controller="Circuits" asp-action="Index">Округи</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">Результати Виборів</a></li>
                        <li><a asp-area="" asp-controller="Districts" asp-action="Index">Дільниці</a></li>
                        <li><a asp-area="" asp-controller="Elections" asp-action="Index">Вибори</a></li>
                        <li><a asp-area="" asp-controller="Vote" asp-action="Index">Голосувати</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>@User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout"><span class="glyphicon glyphicon-log-in"></span></a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav">

                        <li><a asp-area="" asp-controller="Circuits" asp-action="Index">Округи</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">Результати Виборів</a></li>
                        <li><a asp-area="" asp-controller="Districts" asp-action="Index">Дільниці</a></li>
                        <li><a asp-area="" asp-controller="Elections" asp-action="Index">Вибори</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Account" asp-action="Login"><span class="glyphicon glyphicon-user"></span></a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="text-align: center;">
            <p>&copy; 2019 - Не вигадуй</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>